export type ValidSkills =
  | "Credit Analysis"
  | "Equipment Finance"
  | "Commercial Lending"
  | "Financial Statement Review"
  | "Risk Assessment"
  | "Cash Flow Analysis"
  | "Business Credit"
  | "PayNet"
  | "UCC Review"
  | "SOS Review"
  | "Vendor Due Diligence"
  | "Microsoft Excel"
  | "AI Productivity Tools"
  | "Financial Analysis"
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Express"
  | "Express.js" // allow explicit Express.js spelling
  | "JWT"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "TypeScript" // alternate casing used in some entries
  | "JavaScript" // alternate casing used in some entries
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "Google Maps Embed"
  | "WhatsApp API"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "Vite" // build tool used in some projects
  | "Stripe"; // payment integration

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "AI"; // added to support AI/ML related projects

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "about"
  | "skills"
  | "experience"
  | "contact"
  | "resume"
  | "blogs";
